### ISSUE TITLE
Corações desalinhados

### ISSUE THREAD

**Issue by cptx032** [cptx032/chave-mestra#6]
Ao iniciar o jogo os corações das vidas não aparecem alinhados numa única linha:

![image](https://user-images.githubusercontent.com/12432805/111053608-ef748c00-8443-11eb-83f7-31990fe2f63e.png)

Testado no Firefox/Ubuntu

**Comment by di-deus** [comment]
Resolvido, passei em todas as telas deixando-as responsivas. (Caso verifiquem novo erro, favor informar)
